package AssetManagement;


/**
* AssetManagement/AssetServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/idl/asset_management.idl
* Friday, March 7, 2025 10:20:05 AM ICT
*/


// Dinh nghia danh sach chuoi
public abstract class AssetServicePOA extends org.omg.PortableServer.Servant
 implements AssetManagement.AssetServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addAsset", new java.lang.Integer (0));
    _methods.put ("getAllAssets", new java.lang.Integer (1));
    _methods.put ("getAssetByStatus", new java.lang.Integer (2));
    _methods.put ("deleteAsset", new java.lang.Integer (3));
    _methods.put ("getAssetByOwner", new java.lang.Integer (4));
    _methods.put ("getAssetByType", new java.lang.Integer (5));
    _methods.put ("updateStatus", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AssetManagement/AssetService/addAsset
       {
         String id = in.read_string ();
         String type = in.read_string ();
         String owner = in.read_string ();
         String status = in.read_string ();
         this.addAsset (id, type, owner, status);
         out = $rh.createReply();
         break;
       }

       case 1:  // AssetManagement/AssetService/getAllAssets
       {
         String $result[] = null;
         $result = this.getAllAssets ();
         out = $rh.createReply();
         AssetManagement.StringSeqHelper.write (out, $result);
         break;
       }

       case 2:  // AssetManagement/AssetService/getAssetByStatus
       {
         String status = in.read_string ();
         String $result[] = null;
         $result = this.getAssetByStatus (status);
         out = $rh.createReply();
         AssetManagement.StringSeqHelper.write (out, $result);
         break;
       }

       case 3:  // AssetManagement/AssetService/deleteAsset
       {
         String id = in.read_string ();
         this.deleteAsset (id);
         out = $rh.createReply();
         break;
       }

       case 4:  // AssetManagement/AssetService/getAssetByOwner
       {
         String owner = in.read_string ();
         String $result[] = null;
         $result = this.getAssetByOwner (owner);
         out = $rh.createReply();
         AssetManagement.StringSeqHelper.write (out, $result);
         break;
       }

       case 5:  // AssetManagement/AssetService/getAssetByType
       {
         String type = in.read_string ();
         String $result[] = null;
         $result = this.getAssetByType (type);
         out = $rh.createReply();
         AssetManagement.StringSeqHelper.write (out, $result);
         break;
       }

       case 6:  // AssetManagement/AssetService/updateStatus
       {
         String id = in.read_string ();
         String status = in.read_string ();
         this.updateStatus (id, status);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AssetManagement/AssetService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AssetService _this() 
  {
    return AssetServiceHelper.narrow(
    super._this_object());
  }

  public AssetService _this(org.omg.CORBA.ORB orb) 
  {
    return AssetServiceHelper.narrow(
    super._this_object(orb));
  }


} // class AssetServicePOA
