package AssetManagement;

/**
* AssetManagement/AssetServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/idl/asset_management.idl
* Friday, March 7, 2025 10:20:05 AM ICT
*/


// Dinh nghia danh sach chuoi
public final class AssetServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public AssetManagement.AssetService value = null;

  public AssetServiceHolder ()
  {
  }

  public AssetServiceHolder (AssetManagement.AssetService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssetManagement.AssetServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssetManagement.AssetServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssetManagement.AssetServiceHelper.type ();
  }

}
