package AssetManagement;


/**
* AssetManagement/AssetServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/idl/asset_management.idl
* Friday, March 7, 2025 10:20:05 AM ICT
*/


// Dinh nghia danh sach chuoi
public interface AssetServiceOperations 
{
  void addAsset (String id, String type, String owner, String status);
  String[] getAllAssets ();
  String[] getAssetByStatus (String status);
  void deleteAsset (String id);
  String[] getAssetByOwner (String owner);
  String[] getAssetByType (String type);
  void updateStatus (String id, String status);
} // interface AssetServiceOperations
