package AssetManagement;


/**
* AssetManagement/ClientServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/idl/asset_management.idl
* Friday, March 7, 2025 10:20:05 AM ICT
*/

public interface ClientServiceOperations 
{
  void addClient (String id, String name);
  String[] getAllClients ();
} // interface ClientServiceOperations
