package AssetManagement;


/**
* AssetManagement/ClientServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/idl/asset_management.idl
* Friday, March 7, 2025 10:20:05 AM ICT
*/

public abstract class ClientServicePOA extends org.omg.PortableServer.Servant
 implements AssetManagement.ClientServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addClient", new java.lang.Integer (0));
    _methods.put ("getAllClients", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AssetManagement/ClientService/addClient
       {
         String id = in.read_string ();
         String name = in.read_string ();
         this.addClient (id, name);
         out = $rh.createReply();
         break;
       }

       case 1:  // AssetManagement/ClientService/getAllClients
       {
         String $result[] = null;
         $result = this.getAllClients ();
         out = $rh.createReply();
         AssetManagement.StringSeqHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AssetManagement/ClientService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientService _this() 
  {
    return ClientServiceHelper.narrow(
    super._this_object());
  }

  public ClientService _this(org.omg.CORBA.ORB orb) 
  {
    return ClientServiceHelper.narrow(
    super._this_object(orb));
  }


} // class ClientServicePOA
