package AssetManagement;

/**
* AssetManagement/ClientServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/idl/asset_management.idl
* Friday, March 7, 2025 10:20:05 AM ICT
*/

public final class ClientServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public AssetManagement.ClientService value = null;

  public ClientServiceHolder ()
  {
  }

  public ClientServiceHolder (AssetManagement.ClientService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssetManagement.ClientServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssetManagement.ClientServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssetManagement.ClientServiceHelper.type ();
  }

}
