package AssetManagement;

/**
* AssetManagement/StorageServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/idl/asset_management.idl
* Friday, March 7, 2025 10:20:05 AM ICT
*/

public final class StorageServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public AssetManagement.StorageService value = null;

  public StorageServiceHolder ()
  {
  }

  public StorageServiceHolder (AssetManagement.StorageService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AssetManagement.StorageServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AssetManagement.StorageServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AssetManagement.StorageServiceHelper.type ();
  }

}
